// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'bego_app_state.freezed.dart';
// optional: Since our BegoAppState class is serializable, we must add this line.
// But if BegoAppState was not serializable, we could skip it.
// part 'bego_app_state.g.dart';

@freezed
class BegoAppState with _$BegoAppState {
  const factory BegoAppState({
    required String appName,
    required String packageName,
    required String version,
  }) = _BegoAppState;
}
