// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'sign_in_sing_up_state.freezed.dart';
// optional: Since our BegoAppState class is serializable, we must add this line.
// But if BegoAppState was not serializable, we could skip it.
// part 'bego_app_state.g.dart';

@freezed
class SignInSignUpState with _$SignInSignUpState {
  const factory SignInSignUpState({
    required String title,
  }) = _SignInSignUpState;
  factory SignInSignUpState.initial() => const SignInSignUpState(title: 'Bego');
}
