// import 'package:freezed_annotation/freezed_annotation.dart';

// // required: associates our `main.dart` with the code generated by Freezed
// part 'be_list_Item_data.freezed.dart';

// @freezed
// class BeListItemData with _$BeListItemData {
//   const factory BeListItemData({
//     required String firstName,
//     required String lastName,
//     required int age,
//   }) = _BeListItemData;

// }

import 'package:flutter/material.dart';

abstract class BeListItemModal {
  BeListItemModal(this.index);
  late final int index;
  Widget? get leading;
  Widget? get trailing;
  String get title;
  String? get subtitle;
  String? get description;
  String? get selected;
  String? get tag;
  List<String>? get captions;
}
