// import 'package:freezed_annotation/freezed_annotation.dart';

// // required: associates our `main.dart` with the code generated by Freezed
// part 'be_list_Item_data.freezed.dart';

// @freezed
// class BeListItemData with _$BeListItemData {
//   const factory BeListItemData({
//     required String firstName,
//     required String lastName,
//     required int age,
//   }) = _BeListItemData;

// }

import 'package:bego_ui/bego_ui_modals.dart';
import 'package:flutter/material.dart';

abstract class BeListItemModal {
  BeListItemModal(this.index);
  late final int index;
  Widget? get leading;
  Widget? get trailing;
  String get title;
  String? get subtitle;
  String? get description;
  String? get tag;
  List<String>? get captions;
  bool? get selected;
  bool? get enabled;
}

/// https://stackoverflow.com/questions/59854088/how-to-convert-a-flutter-string-to-icon-value  look into furter improvement
/// SSD - S=> key S=> value (display) D=>dynamic data (extra value)
/// [BeKeyValIconS3] Key is Integer and value is String
class BeKeyValIconS3 implements BeKeyValue {
  BeKeyValIconS3({
    required this.icon,
    required this.key,
    required String title,
    required this.subtitle,
    required this.description,
  }) : value = title;

  @override
  final String key;

  @override
  final String value;

  String get title => value;

  final String description;
  final String subtitle;

  final IconData icon;

  @override
  String get display => value.toString();

  @override
  bool operator ==(Object other) =>
      other is BeKeyValIconS3 &&
      other.runtimeType == runtimeType &&
      other.key == key;

  @override
  int get hashCode => key.hashCode;
}
