name: bego_client
command:
  version:
    workspaceChangelog: false

packages:
  - applications/**
  - features/**
  - packages/**

scripts:
  sample_cmd:
    name: "Cmd Name"
    description: Greet the world
    run: echo "$GREETING world"
    env:
      GREETING: "Hey"

  prepare: melos bootstrap
  
  upgrade: melos exec  -- flutter pub upgrade --major-versions --

  clean : melos exec flutter clean
  gen_icons: melos exec --scope="uibook" -- "dart utils/gen_icons.dart $MELOS_ROOT_PATH/packages/bego_ui/config lib/widgets/icons && dart format lib/widgets/icons/icons_list.dart"
