name: flutter_salam
command:
  version:
    workspaceChangelog: false

packages:
  - "**"

scripts:
  hello:
    name: hey
    description: Greet the world
    run: echo "$GREETING world"
    env:
      GREETING: "Hey"
  prepare: melos bootstrap
