name: flutter_salam
command:
  version:
    workspaceChangelog: false

packages:
  - "**"

scripts:
  hello:
    name: hey
    description: Greet the world
    run: echo "$GREETING world"
    env:
      GREETING: "Hey"

  prepare: melos bootstrap

  gen_icons: melos exec --scope="uibook" -- "dart utils/gen_icons.dart $MELOS_ROOT_PATH/packages/bego_ui/lib/src/icon/config lib/widgets/icons && dart format lib/widgets/icons/icons_list.dart"
