// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'home_state.freezed.dart';
// optional: Since our BegoAppState class is serializable, we must add this line.
// But if BegoAppState was not serializable, we could skip it.
// part 'bego_app_state.g.dart';

@freezed
class HomeState with _$HomeState {
  const factory HomeState({
    required String title,
  }) = _HomeState;

  factory HomeState.initial() => const HomeState(title: 'Bego');
}
