name: bego_core
description: A new Flutter package project for and by business ocean.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  async: ^2.11.0
  dfunc: ^0.9.0
  flutter:
    sdk: flutter
  # get: #^5.0.0-release-candidate-5
  #   git:
  #     url: https://github.com/BusinessOcean/getx
  #     ref: master # branch name
  http: ^1.0.0
  intl: ^0.18.1
  logging: ^1.2.0
  meta: ^1.9.1
  rxdart: ^0.27.7
  timeago: ^3.4.0

dev_dependencies:
  flutter_lints: ^2.0.3
